# -*- coding: utf-8 -*-
"""database.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hfhQGjd1IuOtQJUrq2S4G0Hc_Lfgtyev
"""

import sqlite3

def init_db():
    conn = sqlite3.connect('cancer_diagnosis.db')
    cursor = conn.cursor()

    # ایجاد جدول کاربران
    cursor.execute('''
    CREATE TABLE IF NOT EXISTS users (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        username TEXT NOT NULL UNIQUE,
        password_hash TEXT NOT NULL,
        email TEXT NOT NULL UNIQUE
    )
    ''')

    # ایجاد جدول پیش‌بینی‌ها
    cursor.execute('''
    CREATE TABLE IF NOT EXISTS predictions (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        user_id INTEGER,
        input_data TEXT NOT NULL,
        prediction_result TEXT NOT NULL,
        prediction_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(user_id) REFERENCES users(id)
    )
    ''')

    conn.commit()
    conn.close()

# ذخیره پیش‌بینی کاربر
def store_prediction(user_id, input_data, prediction_result):
    conn = sqlite3.connect('cancer_diagnosis.db')
    cursor = conn.cursor()

    cursor.execute("""
        INSERT INTO predictions (user_id, input_data, prediction_result)
        VALUES (?, ?, ?)
    """, (user_id, input_data, prediction_result))

    conn.commit()
    conn.close()

# واکشی پیش‌بینی‌های کاربر
def get_user_predictions(user_id):
    conn = sqlite3.connect('cancer_diagnosis.db')
    cursor = conn.cursor()

    cursor.execute("""
        SELECT input_data, prediction_result, prediction_time
        FROM predictions
        WHERE user_id = ?
        ORDER BY prediction_time DESC
    """, (user_id,))

    predictions = cursor.fetchall()
    conn.close()

    return predictions