# -*- coding: utf-8 -*-
"""encryption.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h8lCSiCGO4mulSdGTk9YRITLyZfUhz0B
"""

from cryptography.fernet import Fernet

# تولید کلید برای رمزگذاری (این را فقط یک بار ایجاد کرده و ذخیره کنید)
key = Fernet.generate_key()
cipher_suite = Fernet(key)

# رمزگذاری داده‌ها
def encrypt_data(data):
    encrypted = cipher_suite.encrypt(data.encode('utf-8'))
    return encrypted

# رمزگشایی داده‌ها
def decrypt_data(encrypted_data):
    decrypted = cipher_suite.decrypt(encrypted_data).decode('utf-8')
    return decrypted