# -*- coding: utf-8 -*-
"""security.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X6t0UHPnLfeO79305IDc5Glhdgp_yyKZ
"""

import bcrypt

# هش کردن پسورد
def hash_password(plain_password):
    salt = bcrypt.gensalt()
    hashed = bcrypt.hashpw(plain_password.encode('utf-8'), salt)
    return hashed

# بررسی پسورد
def check_password(plain_password, hashed_password):
    return bcrypt.checkpw(plain_password.encode('utf-8'), hashed_password)